// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: 4CHRelay


#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// Access state array from main file
extern relay_state state;
extern void (*save_state_callback)(void);


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Image2;
//void ui_event_ImgButton1(lv_event_t * e);
lv_obj_t * ui_ImgButton1;
lv_obj_t * ui_Image3;
//void ui_event_ImgButton2(lv_event_t * e);
lv_obj_t * ui_ImgButton2;
lv_obj_t * ui_Image4;
//void ui_event_ImgButton3(lv_event_t * e);
lv_obj_t * ui_ImgButton3;
lv_obj_t * ui_Image5;
//void ui_event_ImgButton4(lv_event_t * e);
lv_obj_t * ui_ImgButton4;
void ui_event_ImgButton5(lv_event_t * e);
lv_obj_t * ui_ImgButton5;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Panel4;
void ui_event_ImgButton6(lv_event_t * e);
lv_obj_t * ui_ImgButton6;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Label8;
lv_obj_t * ui____initial_actions0;

const lv_image_dsc_t * ui_imgset_p[1] = {&ui_img_p1_png};

void btn_event_handler(lv_event_t * e);


///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

// Moved lv_obj_set_user_data and lv_obj_add_event_cb calls into ui_Screen1_screen_init()


void hide_panel_cb(lv_timer_t * timer) {
    lv_obj_add_flag(ui_Panel1, LV_OBJ_FLAG_HIDDEN);
    lv_timer_del(timer);
}

void update_all_buttons_ui() {
  
    _ui_image_set_property(ui_ImgButton1, _UI_IMAGE_PROPERTY_IMAGE,
        state.btn_state[0] ? (uint8_t*)&ui_img_sw_on_png : (uint8_t*)&ui_img_sw_off_png);

    _ui_image_set_property(ui_ImgButton2, _UI_IMAGE_PROPERTY_IMAGE,
        state.btn_state[1] ? (uint8_t*)&ui_img_sw_on_png : (uint8_t*)&ui_img_sw_off_png);

    _ui_image_set_property(ui_ImgButton3, _UI_IMAGE_PROPERTY_IMAGE,
        state.btn_state[2] ? (uint8_t*)&ui_img_sw_on_png : (uint8_t*)&ui_img_sw_off_png);

    _ui_image_set_property(ui_ImgButton4, _UI_IMAGE_PROPERTY_IMAGE,
        state.btn_state[3] ? (uint8_t*)&ui_img_sw_on_png : (uint8_t*)&ui_img_sw_off_png);
}

void btn_event_handler(lv_event_t * e) {
    lv_obj_t * target = lv_event_get_target(e);
    int id = (int)lv_obj_get_user_data(target);  // Get the button ID from UI
    if (id < 0 || id > 4) return;

    // reverse the button state
    state.btn_state[id] = !state.btn_state[id];
    _ui_image_set_property(target, _UI_IMAGE_PROPERTY_IMAGE,
        state.btn_state[id] ? (uint8_t*)&ui_img_sw_on_png : (uint8_t*)&ui_img_sw_off_png);

    // Show the panel with the message
    char msg[32];
    if (state.btn_state[id]) {
        snprintf(msg, sizeof(msg), "RELAY %d IS ON !", id+1); // +1 to match UI button numbering
    } else {
        snprintf(msg, sizeof(msg), "RELAY %d IS OFF !", id+1);
    }
    lv_label_set_text(ui_Label1, msg);

    _ui_flag_modify(ui_Panel1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    lv_timer_create(hide_panel_cb, 3000, NULL);

    if (save_state_callback != NULL) {
        save_state_callback();
    }
}
void ui_event_ImgButton5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Panel4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
void ui_event_ImgButton6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Panel4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
