// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: 4CHRelay

#ifndef _4CHRELAY_UI_H
#define _4CHRELAY_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdio.h>
#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image2;
//void ui_event_ImgButton1(lv_event_t * e);
extern lv_obj_t * ui_ImgButton1;
extern lv_obj_t * ui_Image3;
//void ui_event_ImgButton2(lv_event_t * e);
extern lv_obj_t * ui_ImgButton2;
extern lv_obj_t * ui_Image4;
//void ui_event_ImgButton3(lv_event_t * e);
extern lv_obj_t * ui_ImgButton3;
extern lv_obj_t * ui_Image5;
//void ui_event_ImgButton4(lv_event_t * e);
extern lv_obj_t * ui_ImgButton4;
void ui_event_ImgButton5(lv_event_t * e);
extern lv_obj_t * ui_ImgButton5;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Panel4;
void ui_event_ImgButton6(lv_event_t * e);
extern lv_obj_t * ui_ImgButton6;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui____initial_actions0;

extern lv_obj_t * ui____initial_actions0;
void btn_event_handler(lv_event_t * e);


LV_IMG_DECLARE(ui_img_p1_png);    // assets/p1.png
LV_IMG_DECLARE(ui_img_sw_off_png);    // assets/sw off.png
LV_IMG_DECLARE(ui_img_sw_on_png);    // assets/sw on.png
LV_IMG_DECLARE(ui_img_header_png);    // assets/header.png
LV_IMG_DECLARE(ui_img_info_png);    // assets/info.png
LV_IMG_DECLARE(ui_img_close_png);    // assets/close.png





typedef struct {
    bool btn_state[4]; 
} relay_state;


extern relay_state state;
extern void (*save_state_callback)(void);

void update_all_buttons_ui(void);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
