// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: 4CHRelay

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x141414), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image2, &ui_img_p1_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image2, -81);
    lv_obj_set_y(ui_Image2, -14);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButton1 = lv_imagebutton_create(ui_Image2);
    lv_imagebutton_set_src(ui_ImgButton1, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_sw_off_png, NULL);
    //lv_imagebutton_set_src(ui_ImgButton1, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_sw_on_png, NULL);
    lv_obj_set_height(ui_ImgButton1, 64);
    lv_obj_set_width(ui_ImgButton1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton1, 0);
    lv_obj_set_y(ui_ImgButton1, -8);
    lv_obj_set_align(ui_ImgButton1, LV_ALIGN_CENTER);

    ui_Image3 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image3, &ui_img_p1_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image3, 89);
    lv_obj_set_y(ui_Image3, -12);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButton2 = lv_imagebutton_create(ui_Image3);
    lv_imagebutton_set_src(ui_ImgButton2, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_sw_off_png, NULL);
    //lv_imagebutton_set_src(ui_ImgButton2, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_sw_on_png, NULL);
    lv_obj_set_height(ui_ImgButton2, 64);
    lv_obj_set_width(ui_ImgButton2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton2, 0);
    lv_obj_set_y(ui_ImgButton2, -8);
    lv_obj_set_align(ui_ImgButton2, LV_ALIGN_CENTER);

    ui_Image4 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image4, &ui_img_p1_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image4, -80);
    lv_obj_set_y(ui_Image4, 80);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButton3 = lv_imagebutton_create(ui_Image4);
    lv_imagebutton_set_src(ui_ImgButton3, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_sw_off_png, NULL);
    //lv_imagebutton_set_src(ui_ImgButton3, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_sw_on_png, NULL);
    lv_obj_set_height(ui_ImgButton3, 64);
    lv_obj_set_width(ui_ImgButton3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton3, 0);
    lv_obj_set_y(ui_ImgButton3, -8);
    lv_obj_set_align(ui_ImgButton3, LV_ALIGN_CENTER);

    ui_Image5 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image5, &ui_img_p1_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image5, 88);
    lv_obj_set_y(ui_Image5, 77);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButton4 = lv_imagebutton_create(ui_Image5);
    lv_imagebutton_set_src(ui_ImgButton4, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_sw_off_png, NULL);
    //lv_imagebutton_set_src(ui_ImgButton4, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_sw_on_png, NULL);
    lv_obj_set_height(ui_ImgButton4, 64);
    lv_obj_set_width(ui_ImgButton4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton4, 0);
    lv_obj_set_y(ui_ImgButton4, -8);
    lv_obj_set_align(ui_ImgButton4, LV_ALIGN_CENTER);

    ui_Image1 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image1, &ui_img_header_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, 3);
    lv_obj_set_y(ui_Image1, -90);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel1, 256);
    lv_obj_set_height(ui_Panel1, 32);
    lv_obj_set_x(ui_Panel1, 3);
    lv_obj_set_y(ui_Panel1, 95);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x212E27), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0xE583F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    //lv_label_set_text(ui_Label1, "RELAY 1 IS ON !");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xD91CF7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_Panel2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel2, 256);
    lv_obj_set_height(ui_Panel2, 48);
    lv_obj_set_x(ui_Panel2, 0);
    lv_obj_set_y(ui_Panel2, 18);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x212E27), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0xFBE619), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 8);
    lv_obj_set_y(ui_Label2, -4);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "KHÔNG TÌM THẤY THIẾT BỊ !");
    //lv_label_set_text_fmt(ui_Label2, "%s  %s", LV_SYMBOL_CLOSE, "KHÔNG TÌM THẤY THIẾT BỊ !");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFE800), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &Nunito16px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iconClose = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_iconClose, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_iconClose, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_iconClose, -113);
    lv_obj_set_y(ui_iconClose, -2);
    lv_obj_set_align(ui_iconClose, LV_ALIGN_CENTER);
    lv_label_set_text(ui_iconClose, LV_SYMBOL_CLOSE);
    lv_obj_set_style_text_color(ui_iconClose, lv_color_hex(0xFFE800), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_iconClose, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_iconClose , &lv_font_montserrat_18, 0);

    ui_Panel3 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel3, 256);
    lv_obj_set_height(ui_Panel3, 48);
    lv_obj_set_x(ui_Panel3, 0);
    lv_obj_set_y(ui_Panel3, 18);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel3, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x212E27), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0x0BFD7A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 0);
    lv_obj_set_y(ui_Label3, -4);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    //lv_label_set_text(ui_Label3, "Found board ID : ");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x0BFD7A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &Nunito18px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iconOk = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_iconOk, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_iconOk, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_iconOk, -105);
    lv_obj_set_y(ui_iconOk, -2);
    lv_obj_set_align(ui_iconOk, LV_ALIGN_CENTER);
    lv_label_set_text(ui_iconOk,LV_SYMBOL_OK);
    //lv_obj_add_flag(ui_iconOk, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_iconOk, lv_color_hex(0x0BFD7A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_iconOk, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_iconOk, &lv_font_montserrat_18, 0);

    ui_ImgButton5 = lv_imagebutton_create(ui_Screen1);
    lv_imagebutton_set_src(ui_ImgButton5, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_info_png, NULL);
    lv_obj_set_height(ui_ImgButton5, 35);
    lv_obj_set_width(ui_ImgButton5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton5, 127);
    lv_obj_set_y(ui_ImgButton5, -95);
    lv_obj_set_align(ui_ImgButton5, LV_ALIGN_CENTER);

    ui_Panel4 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel4, 300);
    lv_obj_set_height(ui_Panel4, 170);
    lv_obj_set_x(ui_Panel4, 2);
    lv_obj_set_y(ui_Panel4, 27);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel4, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x212E27), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 210, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0xCE7332), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton6 = lv_imagebutton_create(ui_Panel4);
    lv_imagebutton_set_src(ui_ImgButton6, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_close_png, NULL);;
    lv_obj_set_height(ui_ImgButton6, 32);
    lv_obj_set_width(ui_ImgButton6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton6, 130);
    lv_obj_set_y(ui_ImgButton6, -65);
    lv_obj_set_align(ui_ImgButton6, LV_ALIGN_CENTER);

    ui_Label4 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -8);
    lv_obj_set_y(ui_Label4, -64);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "THÔNG TIN THIẾT BỊ KẾT NỐI");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xF56F0B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &Nunito16px, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -80);
    lv_obj_set_y(ui_Label5, -31);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    //lv_label_set_text(ui_Label5, "BOARD ID:");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x1EFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -60);
    lv_obj_set_y(ui_Label6, -3);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    //lv_label_set_text(ui_Label6, "UPTIME:");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0x1EFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -34);
    lv_obj_set_y(ui_Label7, 25);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    //lv_label_set_text(ui_Label7, "MAC:");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0x1EFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -50);
    lv_obj_set_y(ui_Label8, 57);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    //lv_label_set_text(ui_Label8, "FW: 1.0.1/ PANGCRD");
     lv_label_set_text_fmt(ui_Label8,"%s  %s",LV_SYMBOL_OK, "FW: 1.0.1/ PANGCRD");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0x1EFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);


    lv_obj_set_user_data(ui_ImgButton4, (void*)3);
    lv_obj_set_user_data(ui_ImgButton3, (void*)2);
    lv_obj_set_user_data(ui_ImgButton2, (void*)1);
    lv_obj_set_user_data(ui_ImgButton1, (void*)0);
    lv_obj_add_event_cb(ui_ImgButton1, btn_event_handler, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_ImgButton2, btn_event_handler, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_ImgButton3, btn_event_handler, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_ImgButton4, btn_event_handler, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_ImgButton5, ui_event_ImgButton5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton6, ui_event_ImgButton6, LV_EVENT_ALL, NULL);
    
    // lv_obj_add_event_cb(ui_ImgButton1, ui_event_ImgButton1, LV_EVENT_ALL, NULL);
    // lv_obj_add_event_cb(ui_ImgButton2, ui_event_ImgButton2, LV_EVENT_ALL, NULL);
    // lv_obj_add_event_cb(ui_ImgButton3, ui_event_ImgButton3, LV_EVENT_ALL, NULL);
    // lv_obj_add_event_cb(ui_ImgButton4, ui_event_ImgButton4, LV_EVENT_ALL, NULL);

}
